name: sampler
description: A specialized utility for managing sample code in the Flutter repo.
version: 0.2.0
homepage: https://github.com/flutter/flutter

binaries:
  sampler

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.0.0
  args: ^2.0.0
  convert: ^3.0.1
  crypto: ^3.0.1
  file: ^6.1.0
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  path: ^1.8.0
  platform: ^3.0.0
  process: ^4.2.1
  process_runner: ^4.0.0
  recase: ^4.0.0
  snippets: ^0.2.3
  watcher: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
