name: sampler
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

binaries:
  sampler

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.6.1
  args: ^2.0.0
  crypto: ^3.0.1
  file: ^6.1.0
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  path: ^1.8.0
  platform: ^3.0.0
  process: ^4.2.1
  process_runner: ^4.0.0
  recase: ^4.0.0
  snippets:
    path: ../../packages/snippets
  watcher: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
