name: diagram_generator
description: Main app for building API doc assets.

dependencies:
  flutter:
    sdk: flutter
  diagram_capture:
    path: ../../packages/diagram_capture
  diagrams:
    path: ../../packages/diagrams
  path_provider: ^0.4.1
  archive: ^2.0.10
  process: 3.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
