name: diagram_generator
description: Main app for building API doc assets.

dependencies:
  archive: ^2.0.10
  diagram_capture:
    path: ../../packages/diagram_capture
  diagrams:
    path: ../../packages/diagrams
  flutter:
    sdk: flutter
  path_provider: ^0.4.1
  platform: ">=3.0.0-nullsafety.4 <4.0.0"
  process: ">=4.0.0-nullsafety.4 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
