name: diagrams
description: Main app for building API doc assets.

dependencies:
  flutter:
    sdk: flutter
  diagram_capture:
    path: ../packages/diagram_capture
  path_provider: any
  archive: 1.0.33
  process: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

flutter:
  assets:
    - assets/blend_mode_destination.jpeg
    - assets/blend_mode_grid.png
    - assets/blend_mode_source.png
